services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api-task-manager
    environment:
      - PORT=8000
    ports:
      - '8000:8000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    networks:
      - task-manager

  db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - task-manager
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  task-manager:
    driver: bridge

volumes:
  db:
    driver: local
